application:
  repository:
    query-limit-warning-ms: 300

#ADMIN CONFIG
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  first-name: ${ADMIN_FIRSTNAME}
  last-name: ${ADMIN_LASTNAME}
  email: ${ADMIN_EMAIL}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev

  #DATABASE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/food-ecommerce?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Quankane1905@}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true

#Spring doc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

#Config open api to documented application
openapi:
  service:
    api-docs: Food Ecommerce
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY API TITLE}
    version: v1.0.0

#Security Endpoint
security:
  public-endpoints: /oauth2/**, /auth/**, /api/v1/auth/**, /api/v1/payment/**
  user-endpoints: /api/v1/user/**
  admin-endpoints: /api/v1/admin/**, /api/v1/promotion/**, /api/v1/category/**, /api/v1/product/**
  swagger-endpoints: /swagger-ui/**, /v3/api-docs/**, /swagger-ui.html

#JWT Config
jwt:
  expiryHour: 1
  expiryDay: 1
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=