application:
  repository:
    query-limit-warning-ms: 300

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: dev

  #DATABASE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/food-ecommerce?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Quankane1905@}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      use_sql_comments: true

  #SendGrid to verify account or notify
  sendGrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: quanducbui2023@gmail.com
    templateRegistrationId: d-edda5c8267604fdfb5fe08227332ed6c
    templateForgotId: d-fe449caceb8545679f70b7f1f3fabae9
    imagePrev: https://res.cloudinary.com/dgwnoquie/image/upload/v1755789933/image-43_f3kmgh.jpg
    imageNext: https://res.cloudinary.com/dgwnoquie/image/upload/v1755790009/KHACH-BEP-15_bj8u43.jpg
    logo: https://res.cloudinary.com/dgwnoquie/image/upload/v1755791051/HAUS-logo_byhum7.jpg

#Spring doc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

#Config open api to documented application
openapi:
  service:
    api-docs: Food Ecommerce
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY API TITLE}
    version: v1.0.0